<!--
placeholder
这个标签显示表单备注
-->

<h3 class="page-header"><?php echo isset($aCategory['iID']) ? '修改' : '添加' ?>产品类别</h3>
<form id="myform" class="form-horizontal" role="form" method="post" action="">
    <input type="hidden" class="form-control" name="iID"
           value="<?php echo isset($aCategory['iID']) ? $aCategory['iID'] : '' ?>">

    <div class="form-group has-feedback">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 种类名称：</label>

        <div class="col-sm-3">
            <input type="text" class="form-control input-validate" validate="!length:2-20" name="sName"
                   value="<?php echo isset($aCategory['sName']) ? $aCategory['sName'] : '' ?>">
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip">

        </div>
    </div>
    <!--
        <div class="form-group has-feedback">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 种类名称：</label>
            <div class="col-sm-3 has-error">
                <input type="text" class="form-control input-validate" validate="!length:2-20" name="sMenuName" value="<?php echo isset($aCategory['sMenuName']) ? $aCategory['sMenuName'] : '' ?>">
                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                <span class="validate_checktip"></span>
            </div>
        </div>
-->
    <div class="form-group">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 父级种类：</label>

        <div class="col-sm-3 has-success">
            <select name="iParentID" class="form-control input-validate col-sm-10">
                <option value="0">顶级种类</option>
                <?php
                if (!empty($aTree)) {
                    $iCategoryID = isset($aCategory['iParentID']) ? $aCategory['iParentID'] : '';
                    foreach ($aTree as $v) {
                        ?>
                        <option
                            value="<?php echo $v['iID']?>" <?php echo $v['iID'] == $iCategoryID ? 'selected' : '';?>><?php echo ($v['iLevel'] > 0 ? '└' . str_repeat('─', $v['iLevel'] * 2) : '') . $v['sName']?></option>
                    <?php }
                } ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-3">
        <input type="submit" class="btn btn-primary" value="保存">
        <button id="cancel" class="btn" onclick="location.href='<?php echo $sListUrl ?>';return false;">取消</button>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                $.post(form.action, $(form).serialize(), function (ret) {
                    alert(ret.data);
                    if (ret.status) {
                        location.href = '<?php echo $sListUrl; ?>';
                    }
                }, 'json');
                return false;
            }
        });

    });
</script>