<!DOCTYPE HTML>
<html>
<head>
    <title><?php echo isset($aMeta['title']) ? $aMeta['title'] : '' ?></title>
    <meta name="keywords" content="<?php echo isset($aMeta['keywords']) ? $aMeta['keywords'] : '' ?>">
    <meta name="description" content="<?php echo isset($aMeta['description']) ? $aMeta['description'] : '' ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="<?php echo $sStaticRoot ?>/admin/css/dpl-min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $sStaticRoot ?>/admin/css/bui-min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $sStaticRoot ?>/admin/css/main-min.css" rel="stylesheet" type="text/css"/>
</head>
<body>

<div class="header">
    <div class="dl-title">
        <a href="<?php echo $sRoot; ?>" title="银汇天下后台"><!-- 仅仅为了提供文档的快速入口，项目中请删除链接 -->
            <span class="lp-title-port"></span><span class="dl-title-text">银汇天下后台</span>
        </a>
    </div>

    <div class="dl-log">欢迎您，<span class="dl-log-user">**.**@alibaba-inc.com</span><a href="###" title="退出系统"
                                                                                     class="dl-log-quit">[退出]</a><a
            href="http://http://www.builive.com/" title="文档库" class="dl-log-quit">文档库</a>
    </div>
</div>
<div class="content">
    <div class="dl-main-nav">
        <div class="dl-inform">
            <div class="dl-inform-title">贴心小秘书<s class="dl-inform-icon dl-up"></s></div>
        </div>
        <ul id="J_Nav" class="nav-list ks-clear">
            <?php
            if (isset($aData['parent']) && !empty($aData['parent'])) {
                foreach ($aData['parent'] as $key => $value) {
                    ?>
                    <li class="nav-item dl-selected">
                        <div class="nav-item-inner <?php echo $value['sIcon']?>"><?php echo $value['sMenuName']?></div>
                    </li>
            <?php
                }
                unset($aData['parent']);
            }
            ?>
        </ul>
    </div>
    <ul id="J_NavContent" class="dl-tab-conten">

    </ul>
</div>
<script>
    var baseUrl = '<?php echo $sRoot ?>';         //网站的根目录地址，发布到线上时使用
    var jsBase = '<?php echo $sStaticRoot ?>/admin/js';
</script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/admin/js/bui.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/admin/js/config.js"></script>

<script>
    var menu = '<?php echo json_encode($aData['sons']) ?>';
    var config = eval(menu);
    BUI.use('common/main', function () {
        new PageUtil.MainPage({
            modulesConfig: config
        });
    });
</script>
</body>
</html>
