
<div id="main">
    <!-- 首页轮播 start -->
    <div id="actionContainer" style='margin:23px 0px 0px 0px;'>
        <div style='left:0;' class='bigarea' id='leftArea'></div>
        <div style='right:0;' class='bigarea' id='rightArea'></div>
        <!-- <a href="javasciprt:" id="preCircle2"> </a>
        <a href="javasciprt:;" id="nextCircle2"> </a> -->
        <ul  id="mycarousel">
            <li class="v2">
                <a href="http://www.iliangcang.com/i/topic/201507312020" target="_blank">
                    <img src="http://imgs-qn.iliangcang.com/ware/slider/524.jpg"  target="_blank" alt="" title=""/>
                </a>
            </li>
            <li class="v2">
                <a href="http://www.iliangcang.com/i/topic/201508042858" target="_blank">
                    <img src="http://imgs-qn.iliangcang.com/ware/slider/524.jpg"  target="_blank" alt="" title=""/>
                </a>
            </li>
            <li class="v2">
                <a href="http://www.iliangcang.com/i/topic/201507301319" target="_blank">
                    <img src="http://imgs-qn.iliangcang.com/ware/slider/517.jpg?t=1438317947"  target="_blank" alt="" title=""/>
                </a>
            </li>
            <li class="v2">
                <a href="http://www.iliangcang.com/i/topic/201507280749" target="_blank">
                    <img src="http://imgs-qn.iliangcang.com/ware/slider/515.jpg"  target="_blank" alt="" title=""/>
                </a>
            </li>
            <li class="v2">
                <a href="http://www.iliangcang.com/i/topic/201507251645" target="_blank">
                    <img src="http://imgs-qn.iliangcang.com/ware/slider/514.jpg"  target="_blank" alt="" title=""/>
                </a>
            </li>
            <li class="v2">
                <a href="http://www.iliangcang.com/i/topic/201507202455" target="_blank">
                    <img src="http://imgs-qn.iliangcang.com/ware/slider/508.jpg"  target="_blank" alt="" title=""/>
                </a>
            </li>
        </ul>
    </div>
    <div id="actionOpt" style="border-bottom:none; font-size:0px;text-align:center;margin-top:3px;" >
        <a href="javascript:;"  class="v2 checked2"  > </a>
        <a href="javascript:;"  class="v2 "  > </a>
        <a href="javascript:;"  class="v2 "  > </a>
        <a href="javascript:;"  class="v2 "  > </a>
        <a href="javascript:;"  class="v2 "  > </a>
        <a href="javascript:;"  class="v2 "  > </a>
    </div>
    <!-- 首页轮播 end -->

    <!-- <div class="hAdv01">
                          <a href="#" target="_blank"><img src="" title="" ></a>
                    </div> -->

    <div class="hAdv02">
        <div class="item1" style="top:0px;left:0px;">
            <a href="http://www.iliangcang.com/i/shop/list?orderby=add_time" target="_blank"><img src="http://7qn7hi.com1.z0.glb.clouddn.com/ware/orig/2/9/9911.jpg" title="" ></a>
        </div>
        <div class="item2">
            <a href="http://www.iliangcang.com/i/topicapp/201508020452" target="_blank"><img src="http://7qn7hi.com1.z0.glb.clouddn.com/ware/orig/2/9/9912.jpg" title=""  alt=""></a>
        </div>
        <div class="item1" style="top:0px;right:0px;">
            <a href="http://www.iliangcang.com/i/brand/intro/?id=328" target="_blank"><img src="http://7qn7hi.com1.z0.glb.clouddn.com/ware/orig/2/9/9908.jpg" title=""   alt=""></a>
        </div>
        <div class="item1" style="bottom:0px;left:0px;">
            <a href="http://www.iliangcang.com/i/brand/intro/?id=324" target="_blank"><img src="http://7qn7hi.com1.z0.glb.clouddn.com/ware/orig/2/9/9910.jpg" title=""  alt="" ></a>
        </div>
        <div class="item1" style="bottom:0px;right:0px;">
            <a href="http://www.iliangcang.com/i/topicapp/201507301628" target="_blank"><img src="http://7qn7hi.com1.z0.glb.clouddn.com/ware/orig/2/9/9909.jpg" title=""  alt="" ></a>
        </div>
    </div>

    <!--
    <div class="hWeekendRec" style="display:none;">
        <div class="item l">
           <div class="tle">特色商店</div>
        <ul class="lList">
          <li class="first"><a href="/i/brand/intro/?is_intro=1&id=2" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1371.jpg" /></a></li>
          <li><a href="/i/brand/own/?id=48" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1354.jpg" /></a></li>
          <li><a href="/i/brand/own/?id=3" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1399.jpg" /></a></li>
        </ul>
      </div>
      <div class="item r">
        <div class="tle">最热达人</div>
        <ul class="lList64">
          <li class="first"><a href="/i/usermain/my/?id=12596" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1153.png" /></a></li>
          <li><a href="/i/usermain/my/?id=8051" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1344.jpg" /></a></li>
          <li><a href="/i/usermain/my/?id=5735" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1355.jpg" /></a></li>
          <li><a href="/i/usermain/my/?id=108" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1156.png" /></a></li>
          <li><a href="/i/usermain/my/?id=151" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1157.png" /></a></li>

           <li class="first"><a href="/i/usermain/my/?id=1502" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1158.png" /></a></li>
           <li ><a href="/i/usermain/my/?id=56" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1159.png" /></a></li>
          <li><a href="/i/usermain/my/?id=5625" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1160.png" /></a></li>
          <li><a href="/i/usermain/my/?id=68" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1161.png" /></a></li>
          <li><a href="/i/usermain/my/?id=187" target="_blank"><img src="http://images.sowhatshop.net/ware/orig/2/1/1162.png" /></a></li>

        </ul>
      </div>
      <div class="clearNull"></div>
    </div>
    -->

    <div class="hGCtle">人气良品</div>


    <div class="shopListCon styl_3" style="margin-top:20px;">
        <div class="item first" >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=248062" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/248/248062.jpg" title="独白永生花巨型玫瑰" alt="独白永生花巨型玫瑰" /></a>
                <a href="/i/goods/?id=248062" class="goodsInfo" target="_blank">
                    <p class="money">¥299.00</p>
                    <p class="tle">独白永生花巨型玫瑰</p>
                    <p class="desc">
                        你在孤独、悲伤的日子，请悄悄地念一念我的名字，并且说：这世上有人在怀念...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=247" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/247.jpg"/>Gelei Story歌蕾的故事</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="248062" goods_uid="0">368</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=248075" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/248/248075.jpg" title="【summer sale 8折 限时折扣】德国钢珠石英手表（玫瑰金色）（原价：2860元）" alt="【summer sale 8折 限时折扣】德国钢珠石英手表（玫瑰金色）（原价：2860元）" /></a>
                <a href="/i/goods/?id=248075" class="goodsInfo" target="_blank">
                    <p class="money">¥2288.00</p>
                    <p class="tle">【summer sale 8折 限时折扣】德国钢珠石英手表（玫瑰金色）（原价：2860元）</p>
                    <p class="desc">
                        颠覆传统的表盘设计，打破常规三针表盘格局，采用钢珠与磁场的感应力来精...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=328" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/328.jpg"/>LAVARO</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="248075" goods_uid="0">259</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=247703" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/247/247703.jpg?t=1436759192" title="KIKOF 精致陶烧八边形马克杯（下单后10日内发货）" alt="KIKOF 精致陶烧八边形马克杯（下单后10日内发货）" /></a>
                <a href="/i/goods/?id=247703" class="goodsInfo" target="_blank">
                    <p class="money">¥630.00</p>
                    <p class="tle">KIKOF 精致陶烧八边形马克杯（下单后10日内发货）</p>
                    <p class="desc">
                        KIKOF将用纸张可以折出来的形状为概念，从 2D 平面变成3D 水壶、杯...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=297" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/297.jpg?t=1431069910"/>良仓清单</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="247703" goods_uid="0">737</a>
            </div>
        </div>
        <div class="item first" >
            <div class="imgCon">
                <div class="optCon">
                    <span class="optBtn isGift"></span>                    </div>
                <a href="/i/goods/?id=246513" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/246/246513.jpg?t=1433746690" title="镀铜烧瓶型醒酒器（Jug）" alt="镀铜烧瓶型醒酒器（Jug）" /></a>
                <a href="/i/goods/?id=246513" class="goodsInfo" target="_blank">
                    <p class="money">¥1280.00</p>
                    <p class="tle">镀铜烧瓶型醒酒器（Jug）</p>
                    <p class="desc">
                        TANK系列镀铜烧瓶型醒酒器，置水，冰茶以及Pimm&#039;s绝佳。
                        每只Tom Di...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=18" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/18.jpg?t=201407140001"/>Tom Dixon</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="246513" goods_uid="0">344</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=244400" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/244/244400.jpg" title="EIN文化杂志（第四期）" alt="EIN文化杂志（第四期）" /></a>
                <a href="/i/goods/?id=244400" class="goodsInfo" target="_blank">
                    <p class="money">¥50.00</p>
                    <p class="tle">EIN文化杂志（第四期）</p>
                    <p class="desc">
                        一本好杂志有很多标准，这一本希望在热闹的媒介海中辟出一方小天地，盛放...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=262" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/262.jpg"/>EIN</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="244400" goods_uid="0">455</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=232131" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/232/232131.jpg" title="上海铁管椅" alt="上海铁管椅" /></a>
                <a href="/i/goods/?id=232131" class="goodsInfo" target="_blank">
                    <p class="money">¥1980.00</p>
                    <p class="tle">上海铁管椅</p>
                    <p class="desc">
                        当二十年代荷兰人设计出悬臂椅之后，时髦的上海一点没落后；在四、五十年...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=228" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/228.jpg"/>失物招领</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="232131" goods_uid="0">650</a>
            </div>
        </div>
        <div class="item first" >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=246389" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/246/246389.jpg?t=1433235359" title="MODERN系列复古偏光太阳镜" alt="MODERN系列复古偏光太阳镜" /></a>
                <a href="/i/goods/?id=246389" class="goodsInfo" target="_blank">
                    <p class="money">¥758.00</p>
                    <p class="tle">MODERN系列复古偏光太阳镜</p>
                    <p class="desc">
                        这款灵感来自于上世纪30年代，那时的人们在女人味和典雅这两个方面大下...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=293" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/293.jpg"/>Kinsole 清尚</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="246389" goods_uid="0">147</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                    <span class="optBtn isGift"></span>                    </div>
                <a href="/i/goods/?id=231831" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/231/231831.jpg" title="【summer sale 8折 限时折扣】多功能桌面清洁刷（多色）（原价310元）" alt="【summer sale 8折 限时折扣】多功能桌面清洁刷（多色）（原价310元）" /></a>
                <a href="/i/goods/?id=231831" class="goodsInfo" target="_blank">
                    <p class="money">¥248.00</p>
                    <p class="tle">【summer sale 8折 限时折扣】多功能桌面清洁刷（多色）（原价310元）</p>
                    <p class="desc">
                        对生活细节的讲究，显现了一个人对于自身的要求，所以就连扫具也要坚持用...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=227" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/227.jpg?t=1423023865"/>Andrée Jardin</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="231831" goods_uid="0">1232</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                    <span class="optBtn isGift"></span>                    </div>
                <a href="/i/goods/?id=231576" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/231/231576.jpg" title="”DRING GAME“杯垫(六片装)" alt="”DRING GAME“杯垫(六片装)" /></a>
                <a href="/i/goods/?id=231576" class="goodsInfo" target="_blank">
                    <p class="money">¥180.00</p>
                    <p class="tle">”DRING GAME“杯垫(六片装)</p>
                    <p class="desc">
                        izola杯垫是两个主题可供选择：搭便车线，海事，饮酒游戏和欢乐时光。这些...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=214" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/214.jpg"/>izola</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="231576" goods_uid="0">241</a>
            </div>
        </div>
        <div class="item first" >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=247798" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/247/247798.jpg" title="TYBEE 锡罐固体香水" alt="TYBEE 锡罐固体香水" /></a>
                <a href="/i/goods/?id=247798" class="goodsInfo" target="_blank">
                    <p class="money">¥418.00</p>
                    <p class="tle">TYBEE 锡罐固体香水</p>
                    <p class="desc">
                        Tybee岛位于格鲁吉亚海滩下方，靠近萨凡纳，因其居民的诚实质朴而得名。...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=317" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/317.jpg"/>Fulton &amp; Roark</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="247798" goods_uid="0">619</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=248030" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/248/248030.jpg" title="加拿大Precidio儿童吸管杯 " alt="加拿大Precidio儿童吸管杯 " /></a>
                <a href="/i/goods/?id=248030" class="goodsInfo" target="_blank">
                    <p class="money">¥95.00</p>
                    <p class="tle">加拿大Precidio儿童吸管杯 </p>
                    <p class="desc">
                        加拿大专利设计，100%防漏，可盛放水，牛奶，果汁等。也可放入洗碗机内清洗，方...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=297" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/297.jpg?t=1431069910"/>良仓清单</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="248030" goods_uid="0">471</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=102666" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/102/102666.jpg" title="十字罐头开罐器" alt="十字罐头开罐器" /></a>
                <a href="/i/goods/?id=102666" class="goodsInfo" target="_blank">
                    <p class="money">¥355.00</p>
                    <p class="tle">十字罐头开罐器</p>
                    <p class="desc">
                        此款罐头开罐器获得2009年GOOD DESIGN大奖，能够完整地开启罐头盖的时...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=102" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/102.jpg"/>FD STYLE</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="102666" goods_uid="0">122</a>
            </div>
        </div>
        <div class="item first" >
            <div class="imgCon">
                <div class="optCon">
                    <span class="optBtn isGift"></span>                    </div>
                <a href="/i/goods/?id=246467" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/246/246467.jpg" title="新西兰ECO STORE 纯天然有机婴儿羊奶皂" alt="新西兰ECO STORE 纯天然有机婴儿羊奶皂" /></a>
                <a href="/i/goods/?id=246467" class="goodsInfo" target="_blank">
                    <p class="money">¥55.00</p>
                    <p class="tle">新西兰ECO STORE 纯天然有机婴儿羊奶皂</p>
                    <p class="desc">
                        ECO STORE荣获2002年新西兰“绿丝带奖”，所有产品都十分天然,宝宝再娇...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=297" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/297.jpg?t=1431069910"/>良仓清单</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="246467" goods_uid="0">533</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=83026" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/83/83026.jpg" title="彩色玻璃窗衬衫" alt="彩色玻璃窗衬衫" /></a>
                <a href="/i/goods/?id=83026" class="goodsInfo" target="_blank">
                    <p class="money">¥539.00</p>
                    <p class="tle">彩色玻璃窗衬衫</p>
                    <p class="desc">
                        Stained Glass Window Shirt 彩色玻璃窗衬衫，采用清新淡雅色调，亲服纯...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=73" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/73.jpg"/>TACITURNLI</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="83026" goods_uid="0">1060</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=247944" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/247/247944.jpg" title="领带架/围巾架" alt="领带架/围巾架" /></a>
                <a href="/i/goods/?id=247944" class="goodsInfo" target="_blank">
                    <p class="money">¥68.00</p>
                    <p class="tle">领带架/围巾架</p>
                    <p class="desc">
                        手工锻造衣物架

                        以适应不同类型的围巾等衣物

                        重量轻

                        超薄外形

                        手...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=323" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/323.jpg"/>fog linen work</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="247944" goods_uid="0">412</a>
            </div>
        </div>
        <div class="item first" >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=248102" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/248/248102.jpg" title="Madame IBIS水瓶" alt="Madame IBIS水瓶" /></a>
                <a href="/i/goods/?id=248102" class="goodsInfo" target="_blank">
                    <p class="money">¥2100.00</p>
                    <p class="tle">Madame IBIS水瓶</p>
                    <p class="desc">
                        一只雅致而实用的水瓶，如同经典的IBIS系列展现其特有的设计。Madame I...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=318" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/318.jpg"/>GEORG JENSEN</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="248102" goods_uid="0">305</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=248136" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/248/248136.jpg" title="【summer sale 8折 限时折扣】深紫色仿皮露背连衣裙（原价：3190元）" alt="【summer sale 8折 限时折扣】深紫色仿皮露背连衣裙（原价：3190元）" /></a>
                <a href="/i/goods/?id=248136" class="goodsInfo" target="_blank">
                    <p class="money">¥2552.00</p>
                    <p class="tle">【summer sale 8折 限时折扣】深紫色仿皮露背连衣裙（原价：3190元）</p>
                    <p class="desc">
                        Bouquet Fever Bioriod系列设计灵感依旧延续品牌创始以来的电影灵感...
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=135" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/135.jpg?t=1413255010"/>Bouquet Fever</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="248136" goods_uid="0">234</a>
            </div>
        </div>
        <div class="item " >
            <div class="imgCon">
                <div class="optCon">
                </div>
                <a href="/i/goods/?id=248050" target="_blank"><img  src="http://imgs-qn.iliangcang.com/ware/goods/big/2/248/248050.jpg" title="防泼水和式双肩包 灰黑色" alt="防泼水和式双肩包 灰黑色" /></a>
                <a href="/i/goods/?id=248050" class="goodsInfo" target="_blank">
                    <p class="money">¥550.00</p>
                    <p class="tle">防泼水和式双肩包 灰黑色</p>
                    <p class="desc">
                        菩提说第六季升级版
                    </p>
                </a>
            </div>
            <div class="bar">
                <a class="who" href="/i/brand/intro/?id=258" target="_blank"><img src="http://imgs-qn.iliangcang.com/ware/brand/258.jpg"/>FOSTYLE</a>
                <a class="goodsFavCount"  href="javascript:;" onclick="goodsAddFavour(event,this);"  goodsid="248050" goods_uid="0">536</a>
            </div>
        </div>
    </div>

    <p class="clr"></p>
    <div id="pagers" style="text-align:center;"><a href="/i/shop/" target="_blank" class="osm-more" style="margin-top:60px;"></a></div>

    <!-- div id="pager" style="text-align:center;">
        <span class="pageLoading">Loading...</span>
    </div-->

</div>

<script type="text/javascript">
    var scrollHight = 0;//滚动条总长度
    var scrollTop = 0; //滚动动条的位置
    var winH = 0 ; //当前文档可视区域的高度
    var curPos = 0 ; //当前滚动高度
    var dtIndex = 1; //索引
    var isLoading = false;
    jQuery(document).ready(function(){
        //jQuery(window).bind('scroll',showData);
        // lss
        jQuery('#actionContainer').mouseover(function(){
            jQuery('#preCircle2,#nextCircle2').css('opacity',1);
        }).mouseout(function(){
            jQuery('#preCircle2,#nextCircle2').css('opacity',0);
        });
        jQuery('#leftArea,#preCircle2').mouseover(function(){
            jQuery('#preCircle2').css('background-image','url(/images/default/circle_right_arrow1.png)');
        }).mouseout(function(){
            jQuery('#preCircle2').css('background-image','url(/images/default/normal_right.png)');
        });

        jQuery('#rightArea,#nextCircle2').mouseover(function(){
            jQuery('#nextCircle2').css('background-image','url(/images/default/circle_left_arrow1.png)');
        }).mouseout(function(){
            jQuery('#nextCircle2').css('background-image','url(/images/default/normal_left.png)');
        });
    });

    function showData(){
        setTimeout('getHomeData()',2000); //每隔两秒加载一次数据
    }


    function clsOrderBy(ordername,data){
        var url = '/'+base_script+'/class/?';
        if(ordername=="favour_count"){
            var orderType = 'asc';
            if(data.className==""||data.className=="asc") orderType='desc';
            url = url+"&orderby=favour_count&orderType="+orderType;
        }else if(ordername=="add_time"){
            var orderType = 'asc';
            if(data.className==""||data.className=="asc") orderType='desc';
            url = url+"&orderby=add_time&orderType="+orderType;
        }else if(ordername=="price"){
            var priceArr = data.split("-");
            url = url+"&orderby=price&min="+priceArr[0]+"&max="+priceArr[1];
        }else if(ordername=="goods_area"){
            url = url+"&orderby=goods_area&value="+data;
        }
        location.href=url+"#_GLS";
    }

    function getHomeData(){
        winH = document.documentElement.clientHeight;
        scrollHight = document.body.scrollHeight;
        scrollTop = getDocumentBody().scrollTop;
        curPos = winH+scrollTop+250;

        if(isLoading==false&&dtIndex>0&&scrollHight<=curPos){
            isLoading = true;
            jQuery('#pagers').html('<span class="pageLoading">Loading...</span>');
            jQuery.get("/"+base_script+"/bestgoods/?page="+dtIndex,function(data){
                data = jQuery.trim(data);
                if(data==''||dtIndex>4){
                    dtIndex = 0;
                    isLoading = false;
                    jQuery('#bestGoodsList').append(data);
                    jQuery('#pagers').html('<a href="/'+base_script+'/class/" class="osm-more"></a>');
                }else{
                    isLoading = false;
                    dtIndex++;
                    jQuery('#bestGoodsList').append(data);
                    //jQuery('#pager').html('');
                }
            })
        }
    }

    function getDocumentBody(){
        if(window.navigator.appVersion.indexOf('MSIE')!=-1||window.navigator.appName=='Opera'||window.navigator.userAgent.indexOf('Firefox')!=-1){
            return document.documentElement;
        }else{
            return document.body;
        }
    }
</script>

