<?php
return array(
    'language'=>'zh-cn',
    'webname'=>'5ucmsPHP演示站',
    'installdir'=>'/',
    'templatedir'=>'blue2015',
    'indexname'=>'首页',
    'indexview'=>'/',
    'indextemplate'=>'index.html',
    'indexpath'=>'/',
    'httpurl'=>'',
    'defaultext'=>'html',
    'sitepathsplit'=>' &gt; ',
    'picwatermarkimg'=>'/inc/images/watermark.gif',
    'picwatermarkalpha'=>'80',
    'picwatermarktype'=>'9',
    'createhtml'=>'0',
    'maxpagenum'=>'2000',
    'autopinyin'=>'1',
    'getenglishstate'=>'1',
    'remotepic'=>'1',
    'indexpicmode'=>'1',
    'prenextmode'=>'1',
    'changdiyname'=>'1',
    'descriptionupdate'=>'1',
    'seodir'=>'0',
    'templatecache'=>'0',
    'cacheflag'=>'www.5ucms.com',
    'cachetime'=>'60',
    'rewriteext'=>'.html',
    'rewritechannel'=>'channel',
    'rewritecontent'=>'',
    'thumbtype'=>'2',
    'indexkeywords'=>'无忧网络,无忧网络文章管理系统,PHP,MYSQL,Rewrite',
    'indexdescription'=>'无忧网络文章管理系统基于PHP+MYSQL 技术开发,免费,开源,程序小巧,功能强大,可用于博客,企业站,信息综合类的建设,使用本系统请保留官方 www.5ucms.com 的链接',
    'author'=>'Admin,5ucms',
    'source'=>'本站',
);