<!--
placeholder
这个标签显示表单备注
-->

<h3 class="page-header"><?php echo isset($aData['iID']) ? '修改' : '添加' ?>商品</h3>
<form id="myform" class="form-horizontal" role="form" method="post" action="">
    <input type="hidden" class="form-control" name="iID"
           value="<?php echo isset($aData['iID']) ? $aData['iID'] : '' ?>">

    <div class="form-group has-feedback">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 商品名称：</label>

        <div class="col-sm-3">
            <input type="text" class="form-control input-validate" validate="!clength:2-20" name="sName"
                   value="<?php echo isset($aData['sName']) ? $aData['sName'] : '' ?>">
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong>商品描述：</label>

        <div class="col-sm-3 has-feedback">
            <textarea class="form-control" rows="3" validate="!clength:2-200" name="sDesc">
                <?php echo isset($aData['sDesc']) ? $aData['sDesc'] : '' ?>
            </textarea>
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group has-feedback">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 商品成本：</label>

        <div class="col-sm-3">
            <input type="text" class="form-control input-validate" validate="!float:true" name="iCosts"
                   value="<?php echo isset($aData['iCosts']) ? $aData['iCosts'] : '' ?>">
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group has-feedback">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 商品价格：</label>

        <div class="col-sm-3">
            <input type="text" class="form-control input-validate" validate="!float:true" name="iPrice"
                   value="<?php echo isset($aData['iPrice']) ? $aData['iPrice'] : '' ?>">
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group has-feedback">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 代理商提成比例：</label>

        <div class="col-sm-3">
            <input type="text" class="form-control input-validate" validate="!float:true" name="iAgentRate"
                   value="<?php echo isset($aData['iAgentRate']) ? $aData['iAgentRate'] : '' ?>">
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group" id="unlockType">
        <label class="control-label col-sm-2"><strong style="color:red;">*</strong> 解锁类型：</label>

        <div class="col-sm-3">
            <select class="form-control" name="iUnlockType">
                <option value="-1">请选择</option>
                <option
                    value="1" <?php echo isset($aParam['iUnlockType']) && 1 == $aParam['iUnlockType'] ? 'selected' : '' ?>>
                    <?php echo $aUnlockType[1] ?>
                </option>
                <option
                    value="0" <?php echo isset($aParam['iUnlockType']) && 0 == $aParam['iUnlockType'] ? 'selected' : '' ?>>
                    <?php echo $aUnlockType[0] ?>
                </option>
            </select>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group" id="unlocklevel">
        <label class="control-label col-sm-2"><strong style="color:red;">*</strong> 解锁级别：</label>

        <div class="col-sm-3">
            <select name="iUnlockLevel" class="form-control input-validate">
                <option value="-1">请选择</option>
                <?php
                if (!empty($aUnlockLevel)) {
                    $iUnlockLevel = isset($aParam['iUnlockLevel']) ? $aParam['iUnlockLevel'] : '';
                    foreach ($aUnlockLevel as $v) {
                        ?>
                        <option
                            value="<?php echo $v ?>" <?php echo $v == $iUnlockLevel ? 'selected' : ''; ?>><?php echo $v ?>
                            级
                        </option>
                    <?php }
                } ?>
            </select>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group has-feedback" id="unlockpoint">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 解锁所需解锁点：</label>

        <div class="col-sm-3">
            <input type="text" class="form-control input-validate" validate="!float:true" name="iUnlockPoint"
                   value="<?php echo isset($aData['iUnlockPoint']) ? $aData['iUnlockPoint'] : '' ?>">
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 商品分类：</label>

        <div class="col-sm-3">
            <select name="icatID" class="form-control input-validate col-sm-10">
                <option value="-1">请选择</option>
                <?php
                if (!empty($aTree)) {
                    $iCategoryID = isset($aData['icatID']) ? $aData['icatID'] : '';
                    foreach ($aTree as $v) {
                        ?>
                        <option
                            value="<?php echo $v['iID'] ?>" <?php echo $v['iID'] == $iCategoryID ? 'selected' : ''; ?>><?php echo ($v['iLevel'] > 0 ? '└' . str_repeat('─', $v['iLevel'] * 2) : '') . $v['sName'] ?></option>
                    <?php }
                } ?>
            </select>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">推荐与热门：</label>

        <div class="col-sm-3">
            <label class="checkbox-inline">
                <input type="checkbox" name="iIsHot" id="iIsHot"
                       value="1" <?php echo isset($aData['iIsHot']) ? 'checked' : '' ?>> 热门商品
            </label>
            <label class="checkbox-inline">
                <input type="checkbox" name="iIsRecommend" id="iIsRecommend"
                       value="1" <?php echo isset($aData['iIsRecommend']) ? 'checked' : '' ?>> 推荐商品
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 商品缩略图：</label>

        <div class="col-sm-10">
            <input type="hidden" validate="*required:请上传商品缩略图" id="sImage" name="sImage"
                   value="<?php echo isset($aNews['sImage']) ? $aNews['sImage'] : '' ?>">
            <img id="sImageShow" style="width:160px;height:120px;"
                 src="<?php if (isset($aNews['sImage']) && !empty($aNews)) {
                     echo Util_Uri::getNewsImgUrl($aNews['sImage']);
                 } else {
                     echo '';
                 } ?>">
            <input type="button" value="选择" class="plupload" data-target="#sImage" data-img="#sImageShow">
            <span>请上传比例为4:3，尺寸大于400*300的清晰图片，文件大小≤100K支持png、jpg</span>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 商品内容：</label>

        <div class="col-sm-8">
            <?php include(Yaf_G::getViewPath() . '/editor.phtml'); ?>
        </div>
        <div class="col-sm-4 validate_checktip"></div>
    </div>
    <div class="orm-group">
        <label class="col-sm-2 control-label"></label>

        <div class="col-sm-3">
            <input type="submit" class="btn btn-primary" value="保存">
            <button id="cancel" class="btn" onclick="location.href='<?php echo $sListUrl ?>';return false;">取消</button>
        </div>
    </div>
</form>
<script type="text/javascript">
    var sUploadUrl = '<?php echo Yaf_G::getConf('upload', 'url')?>';
    var sDfsViewUrl = '<?php echo Yaf_G::getConf('dfsview', 'url')?>';
    var static_url = '<?php echo $sStaticRoot;?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript">
    var unlockLevelNode;
    var unlockPointNode;
    function initUnlock(event) {
        if (event.val() == -1) {//请选择
            $('#unlocklevel').detach();
            $('#unlockpoint').detach();
        } else if (event.val() == 0) {//级别解锁
            $('#unlockType').after(unlockLevelNode);
            $('#unlockpoint').detach();
        } else if (event.val() == 1) {//解锁点解锁
            $('#unlockType').after(unlockPointNode);
            $('#unlocklevel').detach();
        }
    }
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                if ($("select[name='iUnlockType']").val() == -1) {
                    alert('请选择解锁种类');
                    return false;
                } else if ($("select[name='iUnlockType']").val() == 0 && $("select[name='iUnlockLevel']").val() == -1) {
                    alert('请选择解锁级别');
                    return false;
                } else if ($("select[name='iUnlockType']").val() == 1 && $("input[name='iUnlockPoint']").val() == '') {
                    alert('请填写所需解锁点');
                    return false;
                } else {

                }
                if ($("select[name='icatID']").val() == -1) {
                    alert('请选择商品分类');
                    return false;
                }
                if ($('#sImage').val() == '') {
                    alert('请选择上传商品缩略图');
                    return false;
                }
                if (UE.getEditor('editor').hasContents() == false) {
                    alert('请填写商品内容');
                    return false;
                }
                $.post(form.action, $(form).serialize(), function (ret) {
                    alert(ret.data);
                    if (ret.status) {
                        location.href = '<?php echo $sListUrl; ?>';
                    }
                }, 'json');
                return false;
            }
        });

        //初始化解锁类型相关(尼玛这个要写到validate方法后面，调试一下午)
        unlockLevelNode = $('#unlocklevel').detach();//remove不保留事件
        unlockPointNode = $('#unlockpoint').detach();
        initUnlock($("select[name='iUnlockType']"));

        $("select[name='iUnlockType']").change(function () {
            initUnlock($(this));
        });
    })
    ;

    //编辑器
    UE.getEditor('editor').ready(function () {
        //this是当前创建的编辑器实例
        this.setContent('<?php echo isset($aData['sContent']) ? $aData['sContent'] : ''; ?>');
        this.setHeight(300);
    });
</script>