<style>
    .tubiao {
        font-weight: bold;
        color: red;
        padding-right: 2px;
    }
    .publish-div {
        margin-bottom: 20px;
    }
</style>
<div class="pheader clearfix"><?php echo isset($aNews['iNewsID']) ? '编辑' : '增加' ?>资讯</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iNewsID" type="hidden" value="<?php echo isset($aNews['iNewsID']) ? $aNews['iNewsID'] : '' ?>">

        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 资讯标题：</label>

            <div class="col-sm-10">
                <input name="sTitle" validate="!clength:5-22" type="text"
                       value="<?php echo isset($aNews['sTitle']) ? htmlentities($aNews['sTitle']) : '' ?>"
                       class="form-control input-validate" placeholder="标题不能超过22字">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label "><span class="tubiao">*</span> 短&nbsp;&nbsp;标&nbsp;&nbsp;题：</label>

            <div class="col-sm-10">
                <input name="sShortTitle" validate="*clength:5-15" type="text"
                       value="<?php echo isset($aNews['sShortTitle']) ?  htmlentities($aNews['sShortTitle']) : '' ?>"
                       class="form-control input-validate" placeholder="短标题不能超过15字">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 资讯分类：</label>

            <div class="col-sm-10">
                <select name="iCategoryID" class="form-control input-validate">
                    <?php foreach ($aCategory as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aNews['iCategoryID']) && $aNews['iCategoryID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 作&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;者：</label>

            <div class="col-sm-10">
                <input type="hidden" name="iAuthorID" id="iAuthorID" value="<?php echo isset($aNews['iAuthorID']) ? $aNews['iAuthorID'] : 0 ?>">
                <input type="hidden" name="sSelectAuthor" id="sSelectAuthor" value="<?php echo isset($aNews['sAuthor']) ? $aNews['sAuthor'] : '' ?>">
                <input id="sAuthor" name="sAuthor" validate="!function:authorCheck" type="text"
                       value="<?php echo isset($aNews['sAuthor']) ? $aNews['sAuthor'] : '' ?>"
                       class="form-control input-validate" placeholder="请输入作者，并选择所匹配作者">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">资讯来源：</label>

            <div class="col-sm-10">
                <input name="sSource" validate="url:true" type="text"
                       value="<?php echo isset($aNews['sSource']) ? $aNews['sSource'] : '' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 媒体来源：</label>

            <div class="col-sm-10">
                <input validate="*clength:1-20" name="sMedia" validate="url:true" type="text"
                       value="<?php echo (isset($aNews['sMedia']) && $aNews['sMedia']) ? $aNews['sMedia'] : '房价点评网' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 资讯正文：</label>

            <div class="col-sm-7">
                <textarea name="sContent"
                          id="sContent"><?php echo isset($aNews['sContent']) ? $aNews['sContent'] : '' ?></textarea>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">推送楼盘：</label>

            <div class="col-sm-10">
                <input type="hidden" name="sLoupanID" id="sLoupanID"
                       value="<?php echo isset($aNews['sLoupanID']) ? $aNews['sLoupanID'] : '' ?>">

                <div style="float:left;width:70%">
                    <div class="clear"></div>
                    <div class="selestbeizhu">
                        <span style="float:left;">已选的楼盘：</span>

                        <div id="newsLpSelect" style="">
                            <?php if (!empty($aLoupan)) {
                                foreach ($aLoupan as $k => $v) { ?>
                                    <a href="javascript:void(0);" class="des_post"><span
                                            data-id="<?php echo $k ?>"><?php echo $v ?></span><i
                                            class="icon-remove"></i></a>
                                <?php }
                            } ?>
                        </div>
                    </div>
                    <div class="selestxuanze" id="newslp">
                        <input type="hidden" id="iLoupanID" value="">
                        筛选楼盘: <input type="text" id="sLoupanName" style="width:240px;diaplay:inline"> &nbsp;
                        <input type="button" id="newsLpBtn" value="添  加" class="btn btn-sm">
                    </div>
                </div>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 资讯摘要：</label>

            <div class="col-sm-10">
                <textarea name="sAbstract" rows="3" id="sAbstract" class="form-control input-validate"
                          validate="*clength:60-90" placeholder="摘要需在60-90字范围内"><?php echo isset($aNews['sAbstract']) ? $aNews['sAbstract'] : '' ?></textarea>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 默认图片：</label>

            <div class="col-sm-10">
                <input type="hidden" validate="*required:请上传默认图片" id="sImage" name="sImage"
                       value="<?php echo isset($aNews['sImage']) ? $aNews['sImage'] : '' ?>">
                <img id="sImageShow" style="width:160px;height:120px;"
                     src="<?php if (isset($aNews['sImage']) && !empty($aNews)) { echo Util_Uri::getNewsImgUrl($aNews['sImage']); }else{ echo '';}?>">
                <input type="button" value="选择" class="plupload" data-target="#sImage" data-img="#sImageShow">
                <span class="text-muted">请上传比例为4:3，尺寸大于400*300的清晰图片，文件大小≤100K支持png、jpg</span>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 关键字：</label>

            <div class="col-sm-10">
                <input name="sKeyword" validate="*regexp:/^([^\s]+[\s]?){1,4}[^\s]*$/" type="text"
                       value="<?php echo isset($aNews['sKeyword']) ? $aNews['sKeyword'] : '' ?>"
                       class="form-control input-validate" placeholder="多个关键词之间以空格隔开，最多可输入5个">
                <span class="validate_checktip"></span>
            </div>
            <div class="col-sm-3 validate_checktip"><span></span></div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">资讯标签：</label>

            <div class="col-sm-10">
                <input type="hidden" name="sTag" id="sTag"
                       value="<?php echo isset($aNews['sTag']) ? $aNews['sTag'] : '' ?>">

                <div style="float:left;width:70%">
                    <div class="clear"></div>
                    <div class="selestbeizhu">
                        <span style="float:left;">可选5个标签：</span>

                        <div id="newsTagSelect" style="">
                            <?php if (isset($aNews['aTag'])) {
                                foreach ($aNews['aTag'] as $sTag) { if (isset($aTag[$sTag])) { ?>
                                    <a href="javascript:void(0);" class="des_post" rel="<?=$sTag?>"><span><?php echo $aTag[$sTag] ?></span><i
                                            class="icon-remove"></i></a>
                                <?php }}
                            } ?>
                        </div>
                    </div>
                    <div class="selestxuanze" id="newstags">
                        <?php foreach ($aTag as $iTagID => $sTag) { ?>
                            <a href="javascript:void(0)" rel="<?=$iTagID;?>" <?php
                            if (isset($aNews['aTag']) && in_array($iTagID, $aNews['aTag'])) {
                                echo "class='gray'";
                            }
                            ?>><?php echo $sTag ?></a>
                        <?php } ?>
                    </div>
                </div>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <input type="hidden" name="iCityID" value="<?=$iCurrCityID;?>">
        <div class="form-group">
            <label class="col-sm-2 control-label">发布时间：</label>

            <div class="col-sm-10">
                <input name="iPublishTime" readonly validate="datetime:true"
                       class="<?php echo (isset($aNews) && $aNews['iStatus'] && $aNews['iPublishStatus'] && $aNews['iPublishTime'] <= time()) ? '' : 'laydatetime'?> form-control input-validate" validate="" type="text"
                       value="<?php echo isset($aNews['iPublishTime']) ? date('Y-m-d H:i:s',
                           $aNews['iPublishTime']) : date('Y-m-d H:i:s',
                           time()) ?>">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="btn-toolbar text-center col-sm-9 publish-div">
            <input type="hidden" name="iOptype" id="iOptype" value="">
            <input type="hidden" name="time" id="iTime" value="<?=time()?>">
            <button id="publish" onclick="$(this.form).attr('must', 1); $( '#iOptype' ).val(1)" class="btn btn-danger">发布</button>
            <?php if (isset($aNews['iNewsID']) && isset($aNews['iPublishStatus']) && 1 == $aNews['iPublishStatus']):?>

            <?php else:?>
            <button id="save" onclick="$(this.form).attr('must', 0); $( '#iOptype' ).val(0)" class="btn btn-primary">保存</button>
            <?php endif;?>
            <button id="preview" onclick="$(this.form).attr('must', 0)" class="btn btn-info">预览</button>
            <button id="cancel" class="btn" onclick="location.href='<?=$sListUrl?>';return false;">取消</button>
            <?php if (!empty($aNews)) {?>
            <a target="_blank" href="<?php echo 'http://' . Util_Common::getConf('news', 'domain') . '/shanghai/news/detail/preview/?id=' . $aNews['iNewsID']?>" class="btn btn-info">保存后预览</a>
            <?php }?>
        </div>
    </form>
</div>
<script type="text/javascript">
    global.sUploadUrl = '<?php echo Yaf_G::getConf('upload', 'url')?>';
    global.sDfsViewUrl = '<?php echo Yaf_G::getConf('dfsview', 'url')?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/ueditor/ueditor.all.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
<script type="text/javascript">
    var sCityCode = "";
    var iTypeID = <?=$iTypeID?>;
    function authorCheck(value, args) {
        var iAuthorID = $('#iAuthorID').val();
        var sSelectAuthor = $('#sSelectAuthor').val();
        var sAuthor = $('#sAuthor').val();
        if (iAuthorID > 0 && sSelectAuthor == sAuthor) {
            return true;
        }
        return false;
    }


    $(function () {
        //富文本编辑框
        var opt = {
            //这里可以选择自己需要的工具按钮名称,此处仅选择如下五个
            toolbars: [['source', 'undo', 'redo', '|',
                'bold', 'italic', 'underline', 'fontborder', 'strikethrough', 'removeformat', 'blockquote', 'pasteplain', '|',
                'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', '|',
                'justifyleft', 'justifycenter', 'justifyright', '|',
                'link', 'unlink', 'horizontal', '|',
                'customstyle', 'paragraph', 'fontfamily', 'fontsize', '|',
                //'imagenone', 'imageleft', 'imageright', 'imagecenter', '|',
                'inserttable', //插入表格
                'insertrow', //前插入行
                'insertcol', //前插入列
                'deleterow', //删除行
                'deletecol', //删除列
                'mergecells', //合并多个单元格
                'deletetable', //删除表格
                'edittable', //表格属性
                'edittd', //单元格属性
                'insertimage']],
            //关闭字数统计
            wordCount: true,
            //关闭elementPath
            elementPathEnabled: true,
            //默认的编辑区域高度
            initialFrameHeight: 100,
            catchRemoteImageEnable: false,
            //更多其他参数，请参考ueditor.config.js中的配置项
            serverUrl: '<?php echo $sFileBaseUrl; ?>/ueditor/'
        };
        //var aue = UE.getEditor('sAbstract', opt);
        var cue = UE.getEditor('sContent', opt);


        //提交表单
        $("#myform").validate({
            submitHandler: function (form) {
                if($('#iOptype').val() == '') {
                    form.action = 'http://<?=(Yaf_G::getConf('news', 'domain'));?>/shanghai/news/detail/preview/';
                    form.target = '_blank';
                    form.submit();
                    return false;
                }
                form.action = '';
                $.post(form.action, $(form).serialize(), function (ret) {

                    if (ret.status) {
                        var sEditUrl = '<?=$sEditUrl?>?id=' + ret.data.iNewsID;
                        var sMsg = ret.data.sMsg;
                    } else {
                        alert(ret.data);
                        return false;
                        //var sEditUrl = location.href;
                        //var sMsg = ret.data;
                    }
                    showNewsMsgTips(sMsg, '<?=$sListUrl?>', sEditUrl, '<?=$sAddUrl?>');
                }, 'json');
                return false;
            }
        });


        //推送楼盘操作
        $('#newsLpSelect a').click(delNewsLp);
        $('#newsLpBtn').click(function () {
            var newval = $('#sLoupanName').val();
            if (newval.length == 0) {
                alert('请输入楼盘！');
                return false;
            }

            var newid = $('#iLoupanID').val();
            if (newid == '') {
                alert('请选择一个楼盘！');
                return false;
            }

            var nowval = $('#sLoupanID').val();
            var tmp = nowval.split(',');
            if (tmp.indexOf(newid) != -1) {
                alert('此搂盘已在推存列表中！');
                return false;
            }
            nowval = nowval.length == 0 ? newid : nowval + ',' + newid;
            $('#sLoupanID').val(nowval);

            var str = '<a href="javascript:void(0);" class="des_post"><span data-id="' + newid + '">' + newval + '</span><i class="icon-remove"></i></a>';
            $('#newsLpSelect').append(str);
            $('#newsLpSelect a').click(delNewsLp);
            $('#sLoupanName').val('');
            $('#iLoupanID').val('');
            return true;
        });
        function delNewsLp() {
            var str = $(this).find('span').data('id');
            var vals = $('#sLoupanID').val().split(',');
            for (var i = 0; i < vals.length; i++) {
                if (vals[i] == str) {
                    vals.splice(i, 1);
                    break;
                }
            }
            $('#sLoupanID').val(vals.join(','));
            $(this).remove();
        }


        //标签操作
        $('#newstags a').click(function () {
            if ($(this).hasClass('gray')) {
                return false;
            }
            var val = $('#sTag').val();
            if (val.split(',').length == 5) {
                alert('只能添加五个房源标签！');
                return false;
            }
            val = val.length == 0 ? $(this).prop('rel') : val + ',' + $(this).prop('rel');
            $('#sTag').val(val);

            var str = '<a href="javascript:void(0);" class="des_post" rel="' + $(this).prop('rel') + '"><span>' + $(this).html() + '</span><i class="icon-remove"></i></a>';
            $('#newsTagSelect').append($(str));
            $(this).addClass('gray');
            $('#newsTagSelect a').click(delNewsTag);
        });
        $('#newsTagSelect a').click(delNewsTag);
        function delNewsTag() {
            var str = $(this).prop('rel');
            var vals = $('#sTag').val().split(',');
            for (var i = 0; i < vals.length; i++) {
                if (vals[i] == str) {
                    vals.splice(i, 1);
                    break;
                }
            }
            $('#sTag').val(vals.join(','));
            $(this).remove();
            $('#newstags a').each(function () {
                if ($(this).prop('rel') == str) {
                    $(this).removeClass('gray');
                }
            })
        }
    });
</script>
<link rel="stylesheet" href="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.css" type="text/css"/>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/unit.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/author.js"></script>
