<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title><?php echo isset($aMeta['title']) ? $aMeta['title'] : '' ?></title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="keywords" content="<?php echo isset($aMeta['keywords']) ? $aMeta['keywords'] : '' ?>">
    <meta name="description" content="<?php echo isset($aMeta['description']) ? $aMeta['description'] : '' ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/css/common.css">
    <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/validate.js"></script>
</head>
<body>
<div class="container"><?php include $_script; ?></div>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/common.js"></script>
<script type="text/javascript"><?php echo @$__showDebugInfo__ ?></script>
</body>
</html>